/* Original procedural factory. Three.js is locally vendored under its MIT license. */
import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {mergeGeometries} from './vendor/BufferGeometryUtils.js';
import {RoomEnvironment} from './vendor/RoomEnvironment.js';
const ANCHORS={intake:[-18,7,0],mixing:[-9,5,-1],quality:[-3,4,-3],packing:[4,4,0],warehouse:[12,6,-2],shipped:[12,3,14]};
const FLOW={intake:[-17,1.1,4],mixing:[-9,1.1,3],quality:[-3,1.1,3],packing:[4,1.1,3],warehouse:[11,1.1,3],shipped:[12,1.1,14]};
class FactoryScene{
 constructor(canvas,labels,onSelect,onSelectAsset){
  Object.assign(this,{canvas,labels,onSelect,selected:'quality',zoom:1,phase:0,dirty:true,groups:{},lots:new Map(),lights:{}});
  this.onSelectAsset=onSelectAsset;this.assets={};this.selectedAsset=null;this.following=null;this.assetSpeed=0;
  this.reduced=matchMedia('(prefers-reduced-motion: reduce)');
  this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
  this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;
  this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;
  this.world=new T.Scene();this.world.background=new T.Color('#dce6ec');this.camera=new T.PerspectiveCamera(38,1,.1,320);
  this.controls=new OrbitControls(this.camera,canvas);Object.assign(this.controls,{enableDamping:true,dampingFactor:.09,minDistance:15,maxDistance:200,maxPolarAngle:Math.PI*.47,minPolarAngle:.2});
  this.controls.addEventListener('change',()=>{this.dirty=true;this.zoom=this.baseDistance/this.camera.position.distanceTo(this.controls.target);});
  this.sun=new T.DirectionalLight('#fff0d8',3.4);this.sun.position.set(-20,35,20);this.sun.castShadow=true;
  Object.assign(this.sun.shadow.camera,{left:-38,right:38,top:32,bottom:-32,near:1,far:100});this.sun.shadow.mapSize.set(2048,2048);this.sun.shadow.bias=-.00025;this.sun.shadow.normalBias=.025;this.world.add(this.sun);
  this.ambient=new T.HemisphereLight('#dceeff','#64755c',2.1);this.world.add(this.ambient);
  const pmrem=new T.PMREMGenerator(this.renderer),room=new RoomEnvironment();this.environment=pmrem.fromScene(room,.04);this.world.environment=this.environment.texture;this.world.environmentIntensity=.55;room.dispose();pmrem.dispose();
  this.mat={};for(const [name,color,metal,rough] of [['white','#e9eef0',.2,.7],['blue','#3c6382',.3,.55],['steel','#bbc7ce',.75,.33],['dark','#2e3941',.25,.6],['orange','#dc8833',.2,.55],['rubber','#21262b',0,.85],['wood','#a47a46',0,.9],['box','#d4bf95',0,.94],['yellow','#e9bd43',0,.7],['glass','#7cbbd3',.25,.18]])this.mat[name]=new T.MeshStandardMaterial({color,metalness:metal,roughness:rough});
  this.mat.glass=new T.MeshPhysicalMaterial({color:'#82b1c5',roughness:.14,metalness:.05,transparent:true,opacity:.38,depthWrite:false});
  for(const kind of['floor','road','grass'])this.mat[kind]=new T.MeshStandardMaterial({map:this.texture(kind),roughness:.95});
  this.geo=new T.BoxGeometry(1,1,1);this.cylGeo=new T.CylinderGeometry(1,1,1,24);
  this.site();this.factory();this.fleet();this.buildContainers();this.batchStatic();
  this.selection=new T.Mesh(new T.RingGeometry(1.6,1.68,64),new T.MeshBasicMaterial({color:'#498ee8',transparent:true,opacity:.85,side:T.DoubleSide,depthWrite:false}));this.selection.rotation.x=-Math.PI/2;this.world.add(this.selection);
  this.resetView();this.setLighting('day');
  const ray=new T.Raycaster(),pointer=new T.Vector2();let down=null;
  canvas.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);
  const pick=e=>{const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);ray.setFromCamera(pointer,this.camera);for(const hit of ray.intersectObjects([...new Set([...Object.values(this.groups),...Object.values(this.assets)])],true)){let o=hit.object;while(o&&!o.userData.assetId&&!o.userData.stage)o=o.parent;if(o)return o.userData;}return null;};
  canvas.addEventListener('pointerup',e=>{const start=down;down=null;if(!start||Math.hypot(e.clientX-start[0],e.clientY-start[1])>5)return;const hit=pick(e);if(hit?.assetId)onSelectAsset(hit.assetId);else if(hit?.stage)onSelect(hit.stage);});
  let hoverTime=0;canvas.addEventListener('pointermove',e=>{if(down||performance.now()-hoverTime<75)return;hoverTime=performance.now();const hit=pick(e),tip=document.getElementById('asset-hover');canvas.style.cursor=hit?'pointer':'grab';if(!this.lastState||!hit?.assetId){tip.hidden=true;return;}const a=window.FeedAssets.snapshot(this.lastState,hit.assetId);tip.textContent=`${a.name} · ${a.status}`;const r=canvas.getBoundingClientRect();tip.style.left=Math.min(e.clientX-r.left+12,this.w-205)+'px';tip.style.top=Math.max(50,Math.min(e.clientY-r.top-40,this.h-65))+'px';tip.hidden=false;});canvas.addEventListener('pointerleave',()=>document.getElementById('asset-hover').hidden=true);
  this.controls.addEventListener('start',()=>{this.following=null;document.getElementById('asset-hover').hidden=true;});
  canvas.addEventListener('contextmenu',e=>e.preventDefault());
  canvas.addEventListener('keydown',e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();const s=new T.Spherical().setFromVector3(this.camera.position.clone().sub(this.controls.target));s.theta+=e.key==='ArrowLeft'?.12:e.key==='ArrowRight'?-.12:0;s.phi=T.MathUtils.clamp(s.phi+(e.key==='ArrowUp'?-.08:e.key==='ArrowDown'?.08:0),.2,1.45);this.camera.position.copy(this.controls.target).add(new T.Vector3().setFromSpherical(s));this.controls.update();this.dirty=true;});
  this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas.parentElement);this.resize();canvas.dataset.renderer='webgl';document.getElementById('scene-loading').hidden=true;
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();document.getElementById('scene-error').hidden=false;});canvas.addEventListener('webglcontextrestored',()=>{document.getElementById('scene-error').hidden=true;this.dirty=true;});
 }
 batchStatic(){
  this.world.updateMatrixWorld(true);
  const excluded=new Set([...Object.values(this.groups),...Object.values(this.assets),this.roof,this.forklift]);
  for(const owner of new Set([this.world,...Object.values(this.groups),...Object.values(this.assets),this.roof])){
   const buckets=new Map(),inverse=owner.matrixWorld.clone().invert();
   const visit=o=>{if(o!==owner&&excluded.has(o))return;if(o.isMesh&&!o.isInstancedMesh){const key=o.material.uuid+String(o.castShadow);if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(o);}for(const child of o.children)visit(child);};visit(owner);
   for(const meshes of buckets.values()){if(meshes.length<2)continue;const geometries=meshes.map(mesh=>mesh.geometry.clone().applyMatrix4(inverse.clone().multiply(mesh.matrixWorld)));const geometry=mergeGeometries(geometries);for(const g of geometries)g.dispose();if(!geometry)continue;const merged=new T.Mesh(geometry,meshes[0].material);merged.castShadow=meshes[0].castShadow;merged.receiveShadow=true;for(const mesh of meshes)mesh.removeFromParent();owner.add(merged);}
  }
 }
 texture(kind){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d');ctx.fillStyle=kind==='floor'?'#c7cccd':kind==='grass'?'#789665':'#4b535a';ctx.fillRect(0,0,256,256);let seed=41;const rnd=()=>{seed=seed*16807%2147483647;return seed/2147483647;};for(let i=0;i<15000;i++){let v=Math.floor(rnd()*90);ctx.fillStyle=`rgba(${v},${v},${v},.08)`;ctx.fillRect(rnd()*256,rnd()*256,1+rnd()*2,1);}if(kind==='floor'){ctx.strokeStyle='#aeb7ba';ctx.strokeRect(0,0,256,256);}if(kind==='grass'){ctx.fillStyle='rgba(213,232,185,.08)';ctx.fillRect(0,0,128,256);}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(kind==='floor'?14:10,kind==='floor'?7:10);t.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());return t;}
 box(g,x,y,z,w,h,d,mat='white',shadow=true){const m=new T.Mesh(this.geo,typeof mat==='string'?this.mat[mat]:mat);m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=shadow;m.receiveShadow=true;g.add(m);return m;}
 cyl(g,x,y,z,r,h,mat='steel',top=r){const m=new T.Mesh(top===r?this.cylGeo:new T.CylinderGeometry(top,r,1,32),this.mat[mat]);m.position.set(x,y,z);m.scale.set(top===r?r:1,h,top===r?r:1);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
 pipe(g,a,b,r=.09,mat='steel'){const p=new T.Vector3(...a),q=new T.Vector3(...b),v=q.clone().sub(p);const m=new T.Mesh(this.cylGeo,this.mat[mat]);m.position.copy(p.add(q).multiplyScalar(.5));m.scale.set(r,v.length(),r);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),v.normalize());m.castShadow=true;g.add(m);return m;}
 sign(g,text,x,y,z,w=3,h=.7,color='#e7eef4',bg='#2c4c68'){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,512,128);ctx.fillStyle=color;ctx.font='bold 48px Segoe UI, Malgun Gothic';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,66);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:t,side:T.DoubleSide}));m.position.set(x,y,z);g.add(m);return m;}
 stage(name){const g=new T.Group();g.userData.stage=name;this.groups[name]=g;this.world.add(g);return g;}
 site(){this.box(this.world,0,-.45,2,55,.8,39,'grass',false);this.box(this.world,0,.01,2,43,.16,29,'road',false);this.box(this.world,-.5,.14,-.4,35,.26,17,'floor',false);for(let x=-23;x<25;x+=3)this.box(this.world,x,.12,17,.95,.015,.1,'white',false);for(let x=-9;x<18;x+=4){this.box(this.world,x,.11,10,.08,.02,4,'yellow',false);this.box(this.world,x+1.6,.11,12,3.2,.02,.08,'yellow',false);}for(let x=-13;x<-5;x+=1.1)this.box(this.world,x,.12,14,.55,.02,2.2,'white',false);for(let x=-26;x<=26;x+=4)this.tree(x,-15);for(let z=-8;z<17;z+=5){this.tree(-25,z);this.tree(25,z);}for(let x=-21;x<25;x+=7){this.box(this.world,x,.4,-12,.14,.65,.14,'steel');this.pipe(this.world,[x,.7,-12],[x+7,.7,-12],.025);this.pipe(this.world,[x,.35,-12],[x+7,.35,-12],.025);}this.sign(this.world,'GRAINWORKS / LOGISTICS',0,.2,18,10,.9,'#d8dfdf','#4b535a').rotation.x=-Math.PI/2;}
 tree(x,z){this.cyl(this.world,x,1,z,.13,2,'wood');for(let i=0;i<3;i++){const m=new T.Mesh(new T.IcosahedronGeometry(1.25-i*.2,1),new T.MeshStandardMaterial({color:['#507b58','#64865b','#779b66'][i],roughness:1}));m.position.set(x+Math.sin(x)*.2,2.1+i*.65,z);m.scale.y=.8;m.castShadow=true;this.world.add(m);}}
 factory(){
  const shell=new T.Group();this.world.add(shell);this.box(shell,0,2.8,-8,33,5.3,.16);this.box(shell,16.5,1.2,0,.16,2.1,16);
  for(let x=-16;x<17;x+=.6)this.box(shell,x,2.85,-7.89,.035,5,.025,'steel',false);
  for(let x=-16;x<=16;x+=4){this.box(shell,x,3,-7.65,.16,5.8,.16,'blue');this.box(shell,x,2.95,7.4,.16,5.6,.16,'blue');this.pipe(shell,[x,5.6,-7.6],[x,6.8,0],.055);this.pipe(shell,[x,6.8,0],[x,5.6,7.4],.055);}
  for(let x=-14;x<=14;x+=4)this.box(shell,x,3.4,-7.84,2.7,1.3,.05,'glass',false);
  this.sign(shell,'GRAINWORKS',-9,4.8,-7.72,6,1);this.sign(shell,'PRODUCTION 01',2,4.8,-7.72,5,.8);this.sign(shell,'FULFILMENT',12,4.8,-7.72,4,.8);
  this.roof=new T.Group();this.world.add(this.roof);this.box(this.roof,0,6.25,3.7,33,.12,8,'blue').rotation.x=.15;this.box(this.roof,0,6.25,-3.7,33,.12,8,'blue').rotation.x=-.15;for(let x=-14;x<15;x+=5)this.box(this.roof,x,6.92,0,3,.07,1.8,'glass');this.box(this.roof,0,2.8,7.9,33,5.3,.16);this.box(this.roof,0,.9,8.01,33,1.1,.06,'blue');for(let x=-14;x<2;x+=4)this.box(this.roof,x,3.6,8.02,2.6,1.1,.04,'glass');for(const x of[8,13]){this.box(this.roof,x,2.15,8.02,3,3.7,.04,'dark');this.box(this.roof,x,4.1,8.06,3.3,.17,.09,'orange');this.sign(this.roof,x===8?'DOCK 01':'DOCK 02',x,4.6,8.05,2,.4);}this.sign(this.roof,'GRAINWORKS',-8,5,8.05,7,.7);this.roof.visible=false;
  const intake=this.stage('intake');for(let x=-20;x<-15;x+=2.5){this.cyl(intake,x,4,-3,1.08,5.6);this.cyl(intake,x,7,-3,1.08,.6,'steel',.1);this.cyl(intake,x,1,-3,.18,1.2,'steel',1.08);for(let y=1.8;y<6.8;y+=1){const ring=new T.Mesh(new T.TorusGeometry(1.086,.025,6,40),this.mat.steel);ring.rotation.x=Math.PI/2;ring.position.set(x,y,-3);intake.add(ring);}for(const s of[-1,1])this.box(intake,x+s*.8,.9,-3,.12,1.8,.12,'blue');for(let y=1.5;y<7;y+=.35)this.pipe(intake,[x-.2,y,-1.88],[x+.2,y,-1.88],.025);for(const dx of[-.24,.24])this.pipe(intake,[x+dx,1,-1.88],[x+dx,7,-1.88],.03);this.pipe(intake,[x,6,-3],[-11,6,-3],.13);}
  this.box(intake,-18,.35,3,4,.4,4,'steel');this.box(intake,-18,.56,3,3,.05,3,'dark');this.sign(intake,'RAW MATERIAL',-18,1.5,4.5,3,.55);
  const mixing=this.stage('mixing');for(let x=-12;x<=-8;x+=3.4){this.cyl(mixing,x,2.8,-2,1.2,3.5);this.cyl(mixing,x,4.8,-2,1.2,.5,'steel',.5);this.cyl(mixing,x,.7,-2,.35,.8,'steel',1.2);for(const z of[-2.8,-1.2])this.box(mixing,x,.7,z,.12,1.2,.12,'blue');this.box(mixing,x+1.45,2,-2,.8,1.2,1,'blue');this.pipe(mixing,[x,4.9,-2],[x,6,-2],.12);this.pipe(mixing,[x,6,-2],[-17,6,-3],.12);}
  this.box(mixing,-10,1.05,-5,7,.15,2,'steel');for(let x=-13;x<-6;x+=1)this.pipe(mixing,[x,1.1,-4],[x,2,-4],.025);this.pipe(mixing,[-13,2,-4],[-6,2,-4],.025);for(let i=0;i<6;i++)this.box(mixing,-13+i*.22,.2+i*.15,-3.3,.7,.15,1.1,'steel');
  const quality=this.stage('quality');this.box(quality,-2,1.45,-4.6,4,2.6,4.5);this.box(quality,-2,1.65,-2.32,3.8,1.9,.04,'glass');this.box(quality,.02,1.65,-4.5,.04,1.9,4,'glass');this.box(quality,-2,2.9,-4.6,4.2,.12,4.7,'blue');this.sign(quality,'QUALITY LAB',-2,2.65,-2.25,3,.45);for(let x=-3.2;x<0;x+=1.2){this.box(quality,x,1,-3.1,.8,.1,.7);this.box(quality,x,1.4,-3.2,.5,.55,.08,'dark');}
  const packing=this.stage('packing');for(let x=2;x<=6;x+=3){this.box(packing,x,1.2,-2,2.1,2,2.5);this.box(packing,x,1.7,-.71,1.7,1.1,.04,'glass');this.box(packing,x,2.35,-2,2.3,.2,2.7,'blue');this.box(packing,x,1.2,-.62,.55,.9,.08,'dark');this.box(packing,x,1.35,-.55,.4,.3,.02,'glass');this.cyl(packing,x,3,-2,.6,1.2,'steel',1);}
  this.conveyor(mixing,-13,0,9);this.conveyor(quality,-4,0,5);this.conveyor(packing,1,0,7);this.conveyor(packing,1,4,7);
  const warehouse=this.stage('warehouse'),cartons=[];this.registerAsset('WH-01',warehouse,[12,6,-2]);for(let x=9;x<=14;x+=2.4)for(let z=-5.5;z<=1;z+=3){for(const dx of[-.85,.85])for(const dz of[-.7,.7])this.box(warehouse,x+dx,2.55,z+dz,.11,4.7,.11,'blue');for(let y=.65;y<=4.7;y+=1.3){this.box(warehouse,x,y,z,1.85,.12,1.6,'orange');for(let dx=-.5;dx<=.5;dx+=.5)for(let dz=-.4;dz<=.4;dz+=.8)cartons.push([x+dx,y+.43,z+dz]);}this.pipe(warehouse,[x-.85,.3,z+.7],[x+.85,4.8,z+.7],.035);}
  const instances=new T.InstancedMesh(this.geo,this.mat.box,cartons.length),m=new T.Matrix4();cartons.forEach((p,i)=>{m.compose(new T.Vector3(...p),new T.Quaternion(),new T.Vector3(.46,.65,.65));instances.setMatrixAt(i,m);});instances.castShadow=true;instances.receiveShadow=true;warehouse.add(instances);
  for(let x=9;x<16;x+=2.5)this.pallet(warehouse,x,6.2,3);for(let x=-14;x<15;x+=3){this.box(this.world,x,.3,5.2,2.5,.025,.065,'yellow',false);this.box(this.world,x,.3,6.5,2.5,.025,.065,'yellow',false);}
  for(const [name,g] of Object.entries(this.groups)){const p=FLOW[name];const light=this.cyl(g,p[0],2.5,p[2],.09,.25,'yellow');light.material=this.mat.yellow.clone();this.lights[name]=light;}
  this.person(-4,5,'orange');this.person(5,-4,'blue');this.person(14,5,'yellow');
 }
 conveyor(g,x,z,len){this.box(g,x+len/2,.9,z,len,.25,1,'steel');this.box(g,x+len/2,1.04,z,len,.03,.8,'dark');for(let a=x+.25;a<x+len;a+=.35)this.cyl(g,a,1.06,z,.045,.82).rotation.x=Math.PI/2;for(let a=x+.4;a<x+len;a+=2)for(const dz of[-.4,.4])this.box(g,a,.56,z+dz,.07,.7,.07,'steel');}
 pallet(g,x,z,layers=2){for(let i=-1;i<=1;i++)this.box(g,x+i*.42,.4,z,.3,.08,1.3,'wood');for(const dz of[-.45,.45])this.box(g,x,.3,z+dz,1.2,.18,.18,'wood');for(let y=0;y<layers;y++)for(const dx of[-.3,.3])for(const dz of[-.3,.3]){this.box(g,x+dx,.64+y*.52,z+dz,.55,.49,.55,'box');this.box(g,x+dx,.64+y*.52,z+dz,.07,.5,.557,'wood',false);}}
 fleet(){const shipped=this.stage('shipped');for(let x=8;x<=13;x+=5){this.box(shipped,x,.8,8.1,3,.9,.4,'dark');this.sign(shipped,x===8?'DOCK 01':'DOCK 02',x,1.6,8.34,2,.45);const truck=this.truck(shipped,x,12.1,x===8?'blue':'white');this.registerAsset(x===8?'TRK-01':'TRK-02',truck,[0,3.3,2]);this.sign(truck,x===8?'TRK-01':'TRK-02',0,1.75,4.46,1.5,.35);}this.forklift=new T.Group();this.world.add(this.forklift);const f=this.forklift;this.box(f,0,.7,0,1.1,.7,1.7,'orange');this.box(f,0,1.8,-.2,1.2,.1,1.5,'dark');for(const x of[-.48,.48]){this.box(f,x,1.3,-.8,.06,1,.06,'dark');this.box(f,x,1.3,.5,.06,1,.06,'dark');this.box(f,x,1,.9,.07,1.7,.08,'steel');this.box(f,x,.4,1.45,.09,.07,1.2,'steel');}this.box(f,0,1.1,.05,.5,.3,.5,'rubber');for(const x of[-.58,.58])for(const z of[-.55,.55])this.cyl(f,x,.48,z,.25,.16,'rubber').rotation.z=Math.PI/2;this.pallet(f,0,1.3,1);f.position.set(5,0,9);f.rotation.y=Math.PI/2;this.registerAsset('FL-01',f,[0,2.7,0]);}
 truck(g,x,z,color){const t=new T.Group();t.position.set(x,0,z);g.add(t);this.box(t,0,1.8,-.7,2.2,2.7,5.6);this.box(t,0,.8,0,2,.25,8,'dark');for(let a=-3.3;a<2;a+=.16)this.box(t,0,1.8,a,2.21,2.5,.025,'steel',false);this.box(t,0,1.5,3.4,2.3,2.1,2,color);this.box(t,0,2.02,4.42,1.95,.65,.025,'glass');this.box(t,0,1.1,4.43,2.05,.36,.04,'dark');for(const dx of[-.7,.7])this.box(t,dx,1.15,4.46,.35,.13,.025);for(const dx of[-1.13,1.13])for(const zz of[-2.4,-1.4,3.5]){this.cyl(t,dx,.62,zz,.49,.25,'rubber').rotation.z=Math.PI/2;this.cyl(t,dx*1.02,.62,zz,.25,.26).rotation.z=Math.PI/2;}this.sign(t,'GRAINWORKS',0,2,-3.52,1.9,.5);return t;}
 registerAsset(id,group,anchor){group.userData.assetId=id;group.userData.anchor=new T.Vector3(...anchor);this.assets[id]=group;}
 buildContainers(){for(const [id,x,color] of [['CNT-01',-18,'blue'],['CNT-02',-10,'white']]){const g=new T.Group();g.position.set(x,0,10.5);this.world.add(g);this.box(g,0,1.6,0,6.3,2.6,2.5,color);for(let a=-3;a<=3;a+=.22){this.box(g,a,1.6,1.27,.055,2.4,.06,'steel',false);this.box(g,a,2.92,0,.055,.04,2.5,'steel',false);}this.box(g,3.17,1.6,0,.04,2.5,2.5,'steel');for(const z of[-.6,.6])this.pipe(g,[3.22,.5,z],[3.22,2.7,z],.025,'dark');this.sign(g,id,0,2.1,1.34,3,.55);this.sign(g,id==='CNT-01'?'RAW MATERIAL':'OUTBOUND',0,1.25,1.34,3,.4);this.registerAsset(id,g,[0,3.6,0]);}}
 assetPosition(id,anchor=false){const g=this.assets[id];if(!g)return null;g.updateWorldMatrix(true,false);if(id==='WH-01')return new T.Vector3(12,anchor?6:.4,-2);return g.localToWorld(anchor?g.userData.anchor.clone():new T.Vector3(0,.4,0));}
 selectAsset(id){this.selectedAsset=id;this.following=null;if(!id){const p=FLOW[this.selected];this.selection.position.set(p[0],.32,p[2]);}this.dirty=true;}
 focusAsset(id=this.selectedAsset){const p=this.assetPosition(id);if(!p)return;this.following=null;this.controls.target.set(p.x,1,p.z);const d=id==='WH-01'?18:id?.startsWith('CNT')?15:12;this.camera.position.set(p.x+d*.7,d,p.z+d);this.controls.update();this.dirty=true;}
 followAsset(id){if(id!=='FL-01')return;this.focusAsset(id);this.following=id;this.followPosition=this.assetPosition(id);this.dirty=true;}
 updateAssetLabels(state){const placed=[],panel=document.getElementById('asset-panel'),worldRect=this.canvas.getBoundingClientRect(),pr=panel.hidden?null:panel.getBoundingClientRect();for(const button of document.getElementById('asset-labels').children){const id=button.dataset.asset,p=this.assetPosition(id,true)?.project(this.camera);if(!p)continue;button.hidden=p.z>1||Math.abs(p.x)>.93||Math.abs(p.y)>.84;const a=window.FeedAssets.snapshot(state,id,{speed:this.assetSpeed});button.dataset.tone=a.tone;button.classList.toggle('selected',id===this.selectedAsset);button.setAttribute('aria-pressed',id===this.selectedAsset);button.setAttribute('aria-label',`${a.name} 상태 보기`);button.querySelector('small').textContent=a.status;button.title=`${a.name} · ${a.status}`;if(button.hidden)continue;const w=button.offsetWidth,h=button.offsetHeight,x=T.MathUtils.clamp((p.x*.5+.5)*this.w,w/2+6,this.w-w/2-6),origin=(-p.y*.5+.5)*this.h;let y=origin,fit=false;for(const shift of [0,-1,1,-2,2,-3,3]){y=origin+shift*(h+7);if(y<h/2+68||y>this.h-h/2-108)continue;if(placed.some(b=>Math.abs(x-b.x)<(w+b.w)/2+4&&Math.abs(y-b.y)<(h+b.h)/2+4))continue;if(pr&&x+w/2>pr.left-worldRect.left&&x-w/2<pr.right-worldRect.left&&y+h/2>pr.top-worldRect.top&&y-h/2<pr.bottom-worldRect.top)continue;fit=true;break;}button.hidden=!fit;if(!fit)continue;button.style.left=`${x}px`;button.style.top=`${y}px`;placed.push({x,y,w,h});}}

 person(x,z,color){const g=new T.Group();g.position.set(x,0,z);this.world.add(g);this.cyl(g,0,1.25,0,.17,.5,color);this.cyl(g,0,1.64,0,.13,.2,'box');this.cyl(g,0,1.79,0,.18,.12,'yellow');for(const dx of[-.09,.09])this.box(g,dx,.78,0,.13,.48,.16,'dark');for(const dx of[-.23,.23])this.box(g,dx,1.2,0,.09,.4,.12,color);}
 resize(){const r=this.canvas.parentElement.getBoundingClientRect();if(!r.width||!r.height)return;this.w=r.width;this.h=r.height;const narrow=r.width<600;if(this.narrow!==narrow){this.narrow=narrow;this.canvas.parentElement.dataset.narrow=String(narrow);this.resetView();}this.camera.aspect=r.width/r.height;this.camera.updateProjectionMatrix();this.renderer.setSize(r.width,r.height,false);this.dirty=true;}
 resetView(){this.controls.target.set(-1,1,1);const rect=this.canvas.parentElement.getBoundingClientRect(),narrow=rect.width<600,fit=narrow?Math.max(1,Math.min(1.9,.8/(rect.width/rect.height))):1;this.camera.position.set((narrow?47:34)*fit,(narrow?47:32)*fit,(narrow?58:43)*fit);this.baseDistance=this.camera.position.distanceTo(this.controls.target);this.zoom=1;this.controls.update();this.dirty=true;}
 setZoom(z){z=T.MathUtils.clamp(z,.65,3.3);const direction=this.camera.position.clone().sub(this.controls.target).normalize();this.camera.position.copy(this.controls.target).addScaledVector(direction,this.baseDistance/z);this.controls.update();this.dirty=true;}
 focusStage(){const p=ANCHORS[this.selected];this.controls.target.set(p[0],1,p[2]);this.camera.position.set(p[0]+13,15,p[2]+18);this.controls.update();this.dirty=true;}
 setRoof(visible){this.roof.visible=visible;this.dirty=true;this.canvas.dataset.roof=visible?'closed':'cutaway';}
 setLighting(mode){const night=mode==='night',dusk=mode==='dusk';this.world.background.set(night?'#18283b':dusk?'#d6c9bf':'#dce6ec');this.sun.color.set(dusk?'#ffb36a':night?'#7794d9':'#fff0d8');this.sun.intensity=night?.45:dusk?2.7:3.4;this.ambient.intensity=night?.55:dusk?.85:1.05;this.sun.position.set(dusk?-30:-20,dusk?13:35,20);this.renderer.toneMappingExposure=night?1.1:.95;if(!this.lamps){this.lamps=[];for(let x=-10;x<=14;x+=6){const l=new T.PointLight('#cfe6ff',0,13,2);l.position.set(x,4,0);this.world.add(l);this.lamps.push(l);}}for(const l of this.lamps)l.intensity=night?28:dusk?7:0;this.dirty=true;this.canvas.dataset.lighting=mode;}
 draw(state,dt){this.lastState=state;this.controls.update();const moving=window.FeedAssets.snapshot(state,'FL-01').moving&&!this.reduced.matches;this.assetSpeed=0;if(moving){this.phase+=dt;this.forklift.position.x=4+Math.sin(this.phase*.12)*8;this.forklift.rotation.y=Math.cos(this.phase*.12)>=0?Math.PI/2:-Math.PI/2;this.assetSpeed=Math.abs(Math.cos(this.phase*.12)*.96)*3.6;this.dirty=true;}if(this.following){const p=this.assetPosition(this.following),delta=p.clone().sub(this.followPosition);this.camera.position.add(delta);this.controls.target.add(delta);this.followPosition.copy(p);if(delta.lengthSq()>1e-8){this.controls.update();this.dirty=true;}}
  const assetSignature=JSON.stringify([this.selectedAsset,state.running,state.tick,state.settings]);if(assetSignature!==this.assetSignature){this.assetSignature=assetSignature;this.dirty=true;}
  const signature=JSON.stringify([state.lots.map(l=>[l.id,l.stage,l.progress,l.status,l.held]),this.selected,state.alerts?.length]);
  if(signature!==this.signature){this.signature=signature;this.dirty=true;const present=new Set(),indices={};for(const lot of state.lots){present.add(lot.id);let mesh=this.lots.get(lot.id);if(!mesh){mesh=new T.Mesh(this.geo,new T.MeshStandardMaterial({color:'#bfa779',roughness:.7}));mesh.scale.set(.55,.6,.6);mesh.castShadow=true;this.world.add(mesh);this.lots.set(lot.id,mesh);}const p=FLOW[lot.stage]||FLOW.intake,index=indices[lot.stage]||0,held=lot.held||lot.status==='hold';indices[lot.stage]=index+1;mesh.material.color.set(held?'#e5a13b':'#c5ad82');mesh.position.set(p[0]+index*.72+Math.min(1,Number(lot.progress)||0)*.65,p[1],p[2]);}for(const [id,m] of this.lots)if(!present.has(id)){this.world.remove(m);m.material.dispose();this.lots.delete(id);}const p=FLOW[this.selected];this.selection.position.set(p[0],.32,p[2]);for(const [stage,light] of Object.entries(this.lights)){const held=state.lots.some(l=>l.stage===stage&&(l.held||l.status==='hold'));light.material.color.set(held?'#e5a13b':'#5aab84');light.material.emissive.set(held?'#b86512':'#1a7341');light.material.emissiveIntensity=.5;}}
  if(this.selectedAsset){const p=this.assetPosition(this.selectedAsset);this.selection.position.copy(p);}
  if(this.dirty){this.updateLabels(state);this.updateAssetLabels(state);this.renderer.render(this.world,this.camera);this.canvas.dataset.triangles=String(this.renderer.info.render.triangles);this.canvas.dataset.drawCalls=String(this.renderer.info.render.calls);this.canvas.dataset.selectedAsset=this.selectedAsset||'';this.canvas.dataset.following=this.following||'';this.canvas.dataset.forkliftPosition=this.forklift.position.toArray().map(v=>v.toFixed(2)).join(',');this.canvas.dataset.camera=this.camera.position.toArray().map(v=>v.toFixed(2)).join(',');this.dirty=false;}
 }
 updateLabels(state){const placed=[];for(const button of this.labels.children){const stage=button.dataset.stage;if(!ANCHORS[stage])continue;const p=new T.Vector3(...ANCHORS[stage]).project(this.camera);button.hidden=p.z>1||Math.abs(p.x)>.92||Math.abs(p.y)>.86;button.classList.toggle('selected',stage===this.selected);const lots=state.lots.filter(l=>l.stage===stage),held=lots.some(l=>l.status==='hold');button.classList.toggle('has-hold',held);button.title=held?'보류된 Lot이 있습니다. 구역을 선택해 확인하세요.':'구역을 선택해 Lot을 확인하세요.';const small=button.querySelector('small');if(small)small.textContent=`${lots.length} LOT`;if(button.hidden)continue;const x=(p.x*.5+.5)*this.w,w=button.offsetWidth,h=button.offsetHeight;let y=(-p.y*.5+.5)*this.h;for(let i=0;i<6&&placed.some(b=>Math.abs(x-b.x)<(w+b.w)/2+3&&Math.abs(y-b.y)<(h+b.h)/2+3);i++)y+=h+5;button.style.left=`${x}px`;button.style.top=`${y}px`;placed.push({x,y,w,h});}}

}
window.FactoryScene=FactoryScene;
